doctrine:
    dbal:
        default_connection: event_store
        connections:
            event_store:
                url: '%env(resolve:DATABASE_URL)%'
            query_read:
                url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: event
        entity_managers:
            event:
                connection: event_store
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    EventSourcing\Message:
                        type: xml
                        dir: '%kernel.project_dir%/config/event-sourcing'
                        is_bundle: false
                        prefix: EventSourcing
                        alias: EventSourcing
            read:
                connection: query_read
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    App\Projection:
                        mapping: true
                        type: annotation
                        dir: '%kernel.project_dir%/src/App/Projection/'
                        is_bundle: false
                        prefix: App\Projection
                        alias: Projection